#!/usr/bin/env python3
import platform
import shutil
import sys
from pathlib import Path

_DIR = Path(__file__).parent
_PROGRAM_DIR = _DIR.parent
_MODULE = "pymicro_wakeword"
_MODULE_DIR = _PROGRAM_DIR / _MODULE
_SRC_LIB_DIR = _PROGRAM_DIR / "lib"
_DEST_LIB_DIR = _MODULE_DIR / "lib"

machine = platform.machine().lower()
is_arm64 = ("aarch" in machine) or (machine == "arm64")
is_arm32 = machine.startswith("armv") or machine in ("arm", "armhf", "armel")
is_amd64 = machine in ("x86_64", "amd64")
system = sys.platform
platform_name = ""

if system.startswith("linux"):
    if is_arm64:
        platform_name = "linux_arm64"

    if is_arm32:
        platform_name = "linux_armv7l"

    if is_amd64:
        platform_name = "linux_amd64"

if system == "win32":
    if is_amd64:
        platform_name = "windows_amd64"

if system == "darwin":
    if is_arm64:
        platform_name = "darwin_arm64"

if not platform_name:
    raise SystemExit("Unsupported platform")

platform_src_dir = _SRC_LIB_DIR / platform_name
platform_dest_dir = _DEST_LIB_DIR

if _DEST_LIB_DIR.exists():
    shutil.rmtree(_DEST_LIB_DIR)

shutil.copytree(platform_src_dir, platform_dest_dir)
print(platform_dest_dir)
