---
name: Build wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install setuptools wheel build

      - name: Copy tflite library
        run: script/copy_lib

      - name: Build wheel
        run: python -m build --wheel

      - name: Test wheel
        run: |
          python -m venv .venv
          .venv/bin/python3 -m pip install pytest ./dist/*.whl
          .venv/bin/python3 -m pytest tests

      - uses: actions/upload-artifact@v4
        with:
          name: pymicro_wakeword-${{ matrix.os }}
          path: ./dist/*.whl
